2019-03-26 18:18:04,422 ERROR: Exception on /index [GET] [in /var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./app/main/routes.py", line 48, in index
    prev_url=prev_url)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/var/tmp/python3web-project-code/microblog/app/templates/index.html", line 4, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/var/tmp/python3web-project-code/microblog/app/templates/base.html", line 3, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/var/tmp/python3web-project-code/microblog/app/templates/base.html", line 50, in block "content"
    {% block app_content %}{% endblock %}
  File "/var/tmp/python3web-project-code/microblog/app/templates/index.html", line 13, in block "app_content"
    {% include '_post.html' %}
  File "/var/tmp/python3web-project-code/microblog/app/templates/_post.html", line 6, in top-level template code
    <a href="{{ url_for('main.user', username=post.author.username) }}">
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/var/tmp/python3web-project-code/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2182, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2019-03-26 18:23:29,010 INFO: Microblog startup [in ./app/__init__.py:74]
2019-03-26 18:33:10,320 INFO: Microblog startup [in ./app/__init__.py:75]
2019-03-26 18:34:13,021 INFO: Microblog startup [in ./app/__init__.py:75]
2019-03-26 18:34:40,211 INFO: Microblog startup [in /var/tmp/python3web-project-code/microblog/app/__init__.py:75]
2019-03-26 18:36:35,038 INFO: Microblog startup [in ./app/__init__.py:75]
2019-03-26 18:39:10,712 INFO: Microblog startup [in ./app/__init__.py:75]
2019-03-26 18:41:08,096 INFO: Microblog startup [in ./app/__init__.py:75]
2019-03-26 18:42:08,409 INFO: Microblog startup [in ./app/__init__.py:75]
2019-03-26 21:17:08,097 INFO: Microblog startup [in /var/tmp/python3web-project-code/microblog/app/__init__.py:75]
2019-03-26 21:20:59,515 INFO: Microblog startup [in ./app/__init__.py:75]
2019-03-26 21:35:42,339 INFO: Microblog startup [in ./app/__init__.py:79]
2019-03-26 21:37:39,230 INFO: Microblog startup [in ./app/__init__.py:79]
2019-03-26 21:47:29,920 INFO: Microblog startup [in ./app/__init__.py:79]
2019-03-26 22:48:42,248 INFO: Microblog startup [in /var/tmp/python3web-project-code/microblog/app/__init__.py:79]
2019-03-26 23:49:22,502 INFO: Microblog startup [in ./app/__init__.py:79]
